import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'

const nunito = Nunito_Sans({ subsets: ['latin'], weight:['300', '600', '800'] })

export const metadata: Metadata = {
  title: 'Country API',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${nunito.className} bg-bgLight dark:bg-bgDark text-textLight dark:text-textDark`}>
        {/* header */}
        <Header/>
        <div className='container mx-auto'>
        {children}
        </div>
      </body>
    </html>
  )
}
